universe       = vanilla
executable     = /bin/bash
arguments      = /home/jdiya/Htautau-mass-regression/job_scripts/run_train.sh
output         = /home/jdiya/Htautau-mass-regression/logs/train.out
error          = /home/jdiya/Htautau-mass-regression/logs/train.err
log            = /home/jdiya/Htautau-mass-regression/logs/train.log
request_memory = 32GB
request_cpus   = 8
request_gpus   = 1
queue
